sudo: false
language: python
install:
  - pip install pep8 --use-mirrors
python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"
    - "3.4"
before_script:
  - "pep8 --ignore=E501  jdatetime/__init__.py"
  - sudo locale-gen fa_IR
script: python t/test.py
matrix:
    allow_failures:
        - python: "3.2"
        - python: "2.6"
